export const BUTTON_CREATE_TEXT = "Adicionar"
export const BUTTON_UPDATE_TEXT = "Atualizar"
export const BUTTON_SEARCH_TEXT = "Buscar"
export const BUTTON_DELETE_TEXT = "Remover"
export const BUTTON_RESET_TEXT = "Limpar"
export const BUTTON_REMOVE_RELEASE = "Remover dos lançamentos"
export const BUTTON_ADD_RELEASE = "Adicionar aos lançamentos"