export const RENTAL_TITLE = "Aluguéis"
export const RENTAL_LABEL_CLIENT_NAME = "Cliente"
export const RENTAL_LABEL_MOVIE_TITLE = "Filme"
export const RENTAL_LABEL_RENT = "Data de aluguel"
export const RENTAL_LABEL_RETURN = "Data de devolução"